# Generated by Django 3.1 on 2020-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200909_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('imgg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
