# Generated by Django 3.1 on 2020-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='query',
            table='myapp_query',
        ),
    ]
