# Generated by Django 3.1 on 2020-09-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200925_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bwriteby', models.CharField(max_length=50)),
                ('paragraph', models.TextField()),
                ('desc', models.CharField(max_length=200)),
                ('catagory', models.ManyToManyField(to='myapp.Catagory')),
            ],
        ),
    ]
