# Generated by Django 3.1 on 2020-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cmnt', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post_id', models.ManyToManyField(to='myapp.Blog')),
            ],
        ),
    ]
