# Generated by Django 3.1 on 2020-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_about_projectcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100)),
                ('skillper', models.IntegerField()),
                ('lastweek', models.IntegerField()),
                ('lastmonth', models.IntegerField()),
            ],
        ),
    ]
